### ISSUE TITLE
[REQUEST] PUG and 1v1

### ISSUE THREAD

**Issue by freedigin** [b3none/retakes-vip-queue#1]
Hello, Could you make for PUG and 1v1? 

Thanks

**Comment by B3none** [comment]
Hey there Froidice, firstly thanks for using the plugin! I’ll look into whether it’s do-able with these other plugins and get back to you.

**Comment by B3none** [comment]
Looking at the PUG setup, I might need you to explain what you'd like me to do please. How would you like me to put prioritise VIP players in the game?

I have the same question for 1v1 too, what is the desired outcome?

**Comment by freedigin** [comment]
when the game is full, the VIP Player will replace the dead player and the replaced player goes into the spectator, the VIP player goes into the game. Maybe this can also be for 1v1 too

Thanks

**Comment by brianando** [comment]
Nice plugin bro. Good Job <3

**Comment by B3none** [comment]
Since this isn’t an issue with the actual repository I’m going to close the issue.
