### ISSUE TITLE
Queue doesn’t work

### ISSUE THREAD

**Issue by xDavidos** [b3none/retakes-vip-queue#13]
I have a flag but throws me in the queue.
![image](https://user-images.githubusercontent.com/38360572/69729015-43177500-112e-11ea-9c30-9308573f129c.png)

**Comment by gouyeh** [comment]
same here, after updating this plugin not working anymore

**Comment by B3none** [comment]
Can you provide a video of this so I can investigate and see what's going on my end?

**Comment by xDavidos** [comment]
@b3none  
https://youtu.be/6Khp0QLQgZI

**Comment by B3none** [comment]
Have you tried recompiling the plugin? Are there any errors being thrown?

**Comment by xDavidos** [comment]
No there were no mistakes, SM 1.10.0.6454 compiled.

[retakes-vip-queue.zip](https://github.com/b3none/retakes-vip-queue/files/3969392/retakes-vip-queue.zip)

**Comment by B3none** [comment]
If it's not working for you try using version 1.1

**Comment by zahti** [comment]
@b3none I am having the same issue with 1.2.1. Out of curiosity, is it the `ADMFLAG_RESERVATION` variable shown below that performs the check for Admins? Where is that coming from?

```
int FindAdminInArray(Handle waitingQueue)
{
	if (GetArraySize(waitingQueue) != 0)
	{
		int client = 0;
		int index = 0;
		bool found = false;
		
		while (!found && index < GetArraySize(waitingQueue))
		{
			client = GetArrayCell(waitingQueue, index);
			
			if (CheckCommandAccess(client, "skip_queue", ADMFLAG_RESERVATION, false))
			{
				found = true;
			}
			else
			{
				index++;
			}
		}
		
		return found ? client : -1;
	}
	
	return -1;
} 
```

**Comment by sezzny** [comment]
@b3none Hello, the plugin does not work. I have "z" "root" flag. But queue doesn't work.

**Comment by B3none** [comment]
> @b3none Hello, the plugin does not work. I have "z" "root" flag. But queue doesn't work.

Did you try version 1.1?

**Comment by sezzny** [comment]
Where? I couldnt find it.

**Comment by sezzny** [comment]
up

**Comment by B3none** [comment]
Compile and test this version - https://github.com/b3none/retakes-vip-queue/tree/ee016c8a70de8a7b4b4a86cf5dc08fb5cf0fd13e

**Comment by B3none** [comment]
If it works I might need to update the include in this repo

**Comment by st1ng2** [comment]
> Compile and test this version - https://github.com/b3none/retakes-vip-queue/tree/ee016c8a70de8a7b4b4a86cf5dc08fb5cf0fd13e

I can confirm this version is working with the latest Retakes dev version. But with latest Retakes VIP Queue it didn't. (both compiled by me using the latest sourcemod stable version).

**Comment by crashzk** [comment]
I'm still having this same problem, privileged players don't have priority in the queue.

**Comment by crashzk** [comment]
Test the latest commit f0579bf50aef19db294cad691fdbc3683ec3bc3a

https://github.com/b3none/retakes-vip-queue/archive/refs/heads/master.zip

For me it's all right now.

Just remember to compile while the new version is not being merged.

**Comment by B3none** [comment]
https://github.com/b3none/retakes-vip-queue/releases/tag/1.2.2
