### ISSUE TITLE
1.2.1 queue is not functional

### ISSUE THREAD

**Issue by zahti** [b3none/retakes-vip-queue#14]
I have been unable to get this plugin to work with version 1.2.1. There are no compile errors and also no verbose in the server console.

Based on our conversations on Discord, it sounds like the plugin just depends on the admin flag being set for a specific user. This can be checked using command `sm_who` which will output a list of connected users and what flags/roles are set.

> If it's not working for you try using version 1.1

_Originally posted by @b3none in https://github.com/b3none/retakes-vip-queue/issues/13#issuecomment-610296563_

I have tried to compile this commit https://github.com/b3none/retakes-vip-queue/commit/ee016c8a70de8a7b4b4a86cf5dc08fb5cf0fd13e with success! **The plugin works with version 1.1.0!!**

After some testing, it looks like the res flag `a` and root flag `z` are the critical ones for this plugin to function. Anyone with root `z` and/or res `a` flag should get placed at top of the queue and have priority. On the start of next round start/spawn, it will force the players without these flags to Spectate mode. From initial testing, it doesn't seem like the players get placed back into the queue after getting replaced, they get sent to Spectate.

Also, if there are 3 players with the res/root flag set, and `sm_retakes_maxplayers "2"` is set, the plugin breaks and all reserved players get put into the match (seems unintentional). Ideally, it would keep only 2 of the admins in, with the 3rd admin at the top of the waiting queue.

If you have any ideas for what I could try to either update 1.1.0 or fix 1.2.1, I would be willing to make a branch and give it a go!

**Comment by TandelK** [comment]
@zahti As per Commands you can override the flag using admin_overrides with following line 

`"skip_queue" "customflagofyourviphere"`

**Comment by zahti** [comment]
@TandelK What does that help me with? Or are you just trying to help document another command? Sorry, just trying to understand.

**Comment by TandelK** [comment]
If you want custom VIP Flag to use Retake Queue , currently it is bind to flag "a"  which is by default set to Reserved Slot by Sourcemod directly. If you have other flag that you want to use for VIP Queue you can add the above command in admin_overrides.cfg in configs folder to use that flag.

**Comment by zahti** [comment]
@TandelK Awesome thanks for the info! Regarding my issue posted above, 1.2.1 is not functional with flag 'a' however this commit https://github.com/b3none/retakes-vip-queue/commit/ee016c8a70de8a7b4b4a86cf5dc08fb5cf0fd13e is functional with flag 'a'. There is no verbose or errors with 1.2.1 and I am not sure what to go after to get it working.

There are a few problems with the older commit/version which I have outlined above, otherwise I would use this permanently.

**Comment by raufGarayev** [comment]
i am also using version 1.10. but as you mentioned, it doesnt move player to spectate instead of queue, it moves him to LAST queue which is not really good. i think moved player should get to first queue.

**Comment by KillerRoi** [comment]
> 
> 
> If you want custom VIP Flag to use Retake Queue , currently it is bind to flag "a" which is by default set to Reserved Slot by Sourcemod directly. If you have other flag that you want to use for VIP Queue you can add the above command in admin_overrides.cfg in configs folder to use that flag.

Hey @TandelK Can you tell me if I use any other flag like "a" for vips and "b" for admins together "ab" in that command, will that work?

**Comment by TandelK** [comment]
I dont think so its better that you use direct method of using Admins.cfg only to assign same flag with both reserved and admins 


"vip"
a Flag

"admin"
ab Flag

**Comment by KillerRoi** [comment]
> 
> 
> I dont think so its better that you use direct method of using Admins.cfg only to assign same flag with both reserved and admins
> 
> "vip"
> a Flag
> 
> "admin"
> ab Flag

@TandelK so you mean that I only use "ab" to that flag and remove that extra flags for vip? and what do you mean by using admins.cfg?

**Comment by TandelK** [comment]
You cannot assign same function to override to multiple flags. So in order to achieve it directly create a group in admin_groups.cfg and name them VIP and Admin

in VIP Group assign flag "a" and in Admin Group assign flag "ab" this is normal basic sourcemo admins.cfg file. There is no way to use Override with multiple Flags.

**Comment by KillerRoi** [comment]
> 
> 
> You cannot assign same function to override to multiple flags. So in order to achieve it directly create a group in admin_groups.cfg and name them VIP and Admin
> 
> in VIP Group assign flag "a" and in Admin Group assign flag "ab" this is normal basic sourcemo admins.cfg file. There is no way to use Override with multiple Flags.

I still don't get it, creating a group will work? how? I already have groups tbh!

**Comment by crashzk** [comment]
I'm still having this same problem, privileged players don't have priority in the queue.

**Comment by crashzk** [comment]
I compiled it with the changes from the **`full-of-vip-fix`** branch:

https://github.com/b3none/retakes-vip-queue/blob/517022d2f2eec88706cd1f755f262a20969ed5a4/scripting/retakes-vip-queue.sp#L32-L33

![image](https://user-images.githubusercontent.com/32937653/140624138-f7424f9e-66a6-4536-84f9-9686ba14f9b9.png)

As you can see 9 players on the server, none with access to Queue but there are 3 players on the server with access to the Reserved Slot, two of them with root access.

In this screenshot I was on spec and I can't join, it just shows that I'm in the queue to join the team.

![image](https://user-images.githubusercontent.com/32937653/140624287-2ecb7cae-ad76-45f4-b987-57835bdc561d.png)

**Comment by B3none** [comment]
Can you confirm what version of the retakes plugin you are using?

If it's the latest version it looks like this is a bug that should be flagged to Splewis.

Either that, or, we're misinterpreting what the "ranking queue" actually is. My assumption is that it's a queue of people currently playing.

**Comment by crashzk** [comment]
**sm plugins list**
```
[SM] Listing 104 plugins:
  001 "Simple Chat Processor (Redux)" (2.3.0fix) by Simple Plugins, Mini
  002 "ServerAdvertisements3" (3.1.4) by ESK0
  003 <Failed> "CS:GO Disable Agent Models" (1.1) by SAZONISCHE, 8guawong
  004 "SourceTV / GOTV Protector" (1.0) by CrazyHackGUT aka Kruzya
  005 "Weapons & Knives" (1.7.5) by kgns | oyunhost.net
  006 "Fix Disconnect Reason" (1.0.0) by FroidGaming.net
  007 "SourceBans++ Report Plugin" (1.7.0) by RumbleFrog, SourceBans++ Dev Team
  008 "[ ZK Servidores™ ] Console Ads" (1.1) by biielzk, crashzk
  009 "[Lilac] Auto SourceTV Recorder" (1.2.0) by J_Tanzanite
  010 "Reserved Slots" (1.10.0.6513) by AlliedModders LLC
  011 "[ANY] Chat Responder" (1.3.4) by Headline
  012 "SourceBans++ Discord" (1.7.0-51) by Kotik. Fork of RumbleFrog, SourceBans++ Dev Team.
  013 "SourceBans++: SourceComms" (1.7.0) by Alex, SourceBans++ Dev Team
  014 "Basic Comm Control" (1.10.0.6513) by AlliedModders LLC
  015 "Auto Change Map" (1.4) by Mleczam, crashzk
  016 "[Levels Ranks] Core" (v3.1.7 Beta 1) by RoadSide Romeo & Wend4r
  017 <Failed> "[LR] Module - ExStats GeoIP" (v3.1) by RoadSide Romeo
  018 "[LR] Module - Unusual Kills" (v3.1.6 SR2) by Wend4r
  019 "[LR] Module - ExStats Maps" (3.1 F1) by RoadSide Romeo
  020 "[LR] Module - Overlays" (v3.1) by RoadSide Romeo
  021 "[LR] Module - ExStats Weapons" (v3.1) by RoadSide Romeo & Wend4r
  022 "[LR] Module - ExStats Hits" (v3.1) by Wend4r
  023 "[LR] Module - TOP by KDR" (v3.1.5) by Wend4r
  024 "Nextmap" (1.10.0.6513) by AlliedModders LLC
  025 "Console Say" (1.0.1) by abnerfs
  026 "[CS:GO] Disable end match nextmap vote" (30.3.2021) by Bacardi
  027 "[ ZK Servidores™ ] High Ping Kicker" (1.1) by Dr. Api, crashzk
  028 "SwapTeam" (1.2.6fix) by MistaGee, Rogue, crashzk
  029 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)
  030 "AFK Manager" (4.3.0fix) by Rothgar
  031 "TecnoHard GC Level" (1.0.9) by abnerfs
  032 "SourceBans++: Admin Config Loader" (1.7.0) by AlliedModders LLC, SourceBans++ Dev Team
  033 "AntiDLL Handler" (1.7) by JDW
  034 "Basic Commands" (1.10.0.6513) by AlliedModders LLC
  035 "eItems" (0.10) by ESK0 (Original author: SM9)
  036 "Gloves" (1.0.6) by kgns | oyunhost.net
  037 "Rock The Vote Extended" (1.10.0) by Powerlord and AlliedModders LLC
  038 "[CS:GO] Weapon Stickers" (1.2) by quasemago and z1ntex
  039 "SourceBans++: Bans Checker" (1.7.0) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  040 "Sound Commands" (1.10.0.6513) by AlliedModders LLC
  041 "Dano Só Granadas" (1.5.1) by abnerfs
  042 "Default SM Text Replacer" (1.0) by Bacardi & Mitch - Edited: Cruze
  043 "TecnoHard™ Plugins Block" (1.2) by AbNeR @CSB
  044 "TecnoHard Chat Tags" (1.7.1) by abnerfs
  045 "MapChooser Extended" (1.10.2) by Powerlord, Zuko, and AlliedModders LLC
  046 "SourceBans++: Main Plugin" (1.7.0) by SourceBans Development Team, SourceBans++ Dev Team
  047 "[Redirect] Core" (1.0.1 Alpha) by Wend4r
  048 "[ ZK Servidores™ ] Help Menu" (1.0.4) by chundo, emsit, joinedsenses, crashzk, biielzk
  049 "Fun Commands" (1.10.0.6513) by AlliedModders LLC
  050 "[CS:GO] sv_password - bypass players and reserved cookie check" (23.2.2021) by Bacardi
  051 "Cronjobs" (2.0) by dordnung
  052 "Player Analytics" (1.4.2) by Dr. McKay / Bara / sneaK
  053 "Map Nominations Extended" (1.10.0) by Powerlord and AlliedModders LLC
  054 "REGEX word filter" (1.2) by Twilight Suzuka
  055 "Voice of Agents" (1.0) by Romeo
  056 "Admin Menu" (1.10.0.6513) by AlliedModders LLC
  057 "[ ZK Servidores™ ] Valve Menu" (1.0) by Franc1sco franug, crashzk
  058 "Drop Summoner" (1.0.3) by Phoenix (˙·٠●Феникс●٠·˙)
  059 "[VIP] PaintBall" (1.0) by FrozDark (HLModders LLC) (rework by SHKIPPERBEAST)
  060 "[VIP] Stats" (2.6) by R1KO 
  061 "[VIP] FakeRank" (1.0.2) by TiNiK
  062 "[VIP] Boost Ladder" (3.0.0) by diller110 & KOROVKA
  063 "[VIP] Admin" (1.2) by R1KO
  064 "[VIP] No Fall Damage" (1.0.1) by R1KO (skype: vova.andrienko1)
  065 "[VIP] Skybox" (1.1) by White Wolf
  066 "[VIP] Music Kit" (1.1.4) by Pheonix, Felya, crashzk
  067 "[VIP] COIN" (2.0.2) by Pheonix (˙·٠●Феникс●٠·˙) & R1KO, pracc
  068 "[VIP] Exp Multiplier" (1.0) by R1KO (skype: vova.andrienko1)
  069 "[VIP] Healthshot" (1.3) by R1KO (skype: vova.andrienko1) feat. Eneanuch
  070 "[VIP] Additional [For VIP_CORE 3.0]" (1.0.1) by Drumanid
  071 "[CS:GO] Custom MVP Anthem" (1.11) by Kento
  072 "[ ZK Servidores™ ] Block Commands" (1.1) by Geison, crashzk
  073 "NoBots Enforcer" (1.0) by Nikooo777
  074 "[SWGM] Command Listener" (1.2fix) by Someone, crashzk
  075 "Simple Stealth" (1.0) by Potatoz
  076 "Basic Info Triggers" (1.10.0.6513) by AlliedModders LLC
  077 "Anti-Flood" (1.10.0.6513) by AlliedModders LLC
  078 "Player Commands" (1.10.0.6513) by AlliedModders LLC
  079 "Client Preferences" (1.10.0.6513) by AlliedModders LLC
  080 "Tebex SourceMod" (0.0.1) by Tebex
  081 "[ ZK Servidores™ ] View all skins seeds on the console (!ws)" (1.0.0) by biielzk, crashzk
  082 "[VIP] Core" (3.1 DEV) by R1KO
  083 "Admin File Reader" (1.10.0.6513) by AlliedModders LLC
  084 "[Discord] Map Notifications" (1.0.1) by Bara
  085 "SourceBans++: SourceSleuth" (1.7.0) by ecca, SourceBans++ Dev Team
  086 "[Lilac] Little Anti-Cheat" (1.7.1) by J_Tanzanite
  087 "Basic Chat" (1.10.0.6513) by AlliedModders LLC
  088 "Chat Logging" (3.0) by R1KO
  089 "Fun Votes" (1.10.0.6513) by AlliedModders LLC
  090 "[CS:GO] Franug Agents Chooser" (1.2.0) by Franc1sco franug, Romeo, TrueProfessional, Teamkiller324
  091 "Basic Votes" (1.10.0.6513) by AlliedModders LLC
  092 "Discord API" (0.1.106) by Deathknife
  093 "Admin Help" (1.10.0.6513) by AlliedModders LLC
  094 "SM Franug Valve Sprays CSGO" (2.0) by Franc1sco franug, Romeo, crashzk
  095 "[Server-Redirect+] Core" (3.0.1) by Natanel 'LuqS'
  096 "SM Fortnite Emotes Extended" (1.4.2fix) by Kodua, Franc1sco franug, TheBO$$, crashzk
  097 "Steam Works Group Manager" (1.9fix) by Someone, crashzk
  098 "No Dupe Account" (1.5.0 Beta 4) by azalty/rlevet
  099 "CS:GO Retakes" (0.3.4) by splewis
  100 "[Retakes] Bombsite HUD" (2.5.1) by B3none
  101 "CS:GO Retakes: site picker" (0.3.4) by splewis
  102 "[Retakes] VIP Queue" (1.2.1) by B3none
  103 "[Retakes] Autoplant" (2.3.1) by B3none
  104 "Gun Menu" (2.1) by Potatoz, Pepe, crashzk
Errors:
disable_agent_models.smx (CS:GO Disable Agent Models): Required extension "modelch" file("modelch.ext") not running
levels_ranks/levelsranks_exstats_geoip.smx ([LR] Module - ExStats GeoIP): Native "GeoipCity" was not found
```
**- 099 "CS:GO Retakes" (0.3.4) by splewis**
**- 102 "[Retakes] VIP Queue" (1.2.1) by B3none**

**sm version**
```
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6513
    SourcePawn Engine: 1.10.0.6513, jit-x86 (build 1.10.0.6513)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Sep 22 2021 01:46:49
    Built from: https://github.com/alliedmodders/sourcemod/commit/698cc8e
    Build ID: 6513:698cc8e
    http://www.sourcemod.net/
```
### HOW IT SHOULD WORK
I believe the VIP Queue plugin should kick a team player whenever a VIP player tries to join the team.

Example, teams are complete, 5 CT and 4 TR, a spec VIP enters, he then chooses a team to join shows the message to him that he is in the queue to join and when a new round starts a random player should be expelled from the team he chooses and he enters the place.

Is this how it was supposed to work? Or did I get it wrong?

**Comment by TandelK** [comment]
@crashzk Have you given yourself the same flag ? a or just gave z for root access ?  if so please try to give yourself a flag and than try it or any custom flag that you may have defined.

**Comment by B3none** [comment]
> I compiled it with the changes from the **`full-of-vip-fix`** branch:
> 
> https://github.com/b3none/retakes-vip-queue/blob/517022d2f2eec88706cd1f755f262a20969ed5a4/scripting/retakes-vip-queue.sp#L32-L33
> 
> ![image](https://user-images.githubusercontent.com/32937653/140624138-f7424f9e-66a6-4536-84f9-9686ba14f9b9.png)
> 
> As you can see 9 players on the server, none with access to Queue but there are 3 players on the server with access to the Reserved Slot, two of them with root access.
> 
> In this screenshot I was on spec and I can't join, it just shows that I'm in the queue to join the team.
> 
> ![image](https://user-images.githubusercontent.com/32937653/140624287-2ecb7cae-ad76-45f4-b987-57835bdc561d.png)

I've removed the if statement from the master branch, if you can test it again that would help.

https://github.com/b3none/retakes-vip-queue/commit/f0579bf50aef19db294cad691fdbc3683ec3bc3a

**Comment by crashzk** [comment]
> @crashzk Have you given yourself the same flag ? a or just gave z for root access ? if so please try to give yourself a flag and than try it or any custom flag that you may have defined.

Yes, I have both the **`z`** flags set in my steam_id and the **`abcdefghijkl`** flags.

In the case I use SourceBans, SourceMod/SourceBans privilege group system.

>> I've removed the if statement from the master branch, if you can test it again that would help.
>>
>> [f0579bf](https://github.com/b3none/retakes-vip-queue/commit/f0579bf50aef19db294cad691fdbc3683ec3bc3a)

Ok, I will test this new version and return here, thanks.

**Comment by crashzk** [comment]
@b3none now apparently it was, thanks.

Just to confirm, when the player leaves the team for the VIP to enter the place it shows this correct message:
```
	"Replaced"
	{
		"#format" "{1:s}"
		"en" "{1} You have been placed back in the waiting queue because a VIP has taken your spot."
	}
```

I believe these issues can be closed now.

**Comment by B3none** [comment]
Fixed in latest release - https://github.com/b3none/retakes-vip-queue/releases/tag/1.2.2
