### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by 3GaNwO** [b3none/retakes-vip-queue#4]
L 06/01/2019 - 16:50:51: SourceMod error session started
L 06/01/2019 - 16:50:51: Info (map "de_inferno") (file "errors_20190601.log")
L 06/01/2019 - 16:50:51: [SM] Exception reported: Translation failed: invalid client index 1819305298 (arg 5)
L 06/01/2019 - 16:50:51: [SM] Blaming: retakes-vip-queue.smx
L 06/01/2019 - 16:50:51: [SM] Call stack trace:
L 06/01/2019 - 16:50:51: [SM]   [0] PrintToChat
L 06/01/2019 - 16:50:51: [SM]   [1] Line 59, D:\WiT Gaming Stuff\Compiler 1.9\addons\sourcemod\scripting\retakes-vip-queue.sp::Retakes_OnPreRoundEnqueue
L 06/01/2019 - 16:50:51: [SM]   [3] Call_Finish
L 06/01/2019 - 16:50:51: [SM]   [4] Line 689, D:\Rainbox CSGO Stuff\Compiler\compiler2\addons\sourcemod\scripting\retakes.sp::RoundEndUpdates
L 06/01/2019 - 16:50:51: [SM]   [5] Line 578, D:\Rainbox CSGO Stuff\Compiler\compiler2\addons\sourcemod\scripting\retakes.sp::Event_RoundPreStart
L 06/01/2019 - 16:58:35: Error log file session closed.

**Comment by B3none** [comment]
I’ll get around to looking at this.
